### PR TITLE
Add language names to list box

### PR DESCRIPTION
**Pull request by ways2read**
Add language names to list box based on the language codes derived from the folder names.

### CODE REVIEW

**Comment by NSoiffer** [comment]
I think it is better to just define the languages as list directly. I've linked a file with the definition in it to make your life easier.

I don't know github well enough to know how to modify your PR myself, so I'm afraid I pushing this back to you...
[new language dictionary](https://github.com/NSoiffer/MathCATForPython/files/10311445/lang.txt)

**Comment by ways2read** [comment]
Please check if you are happy to merge this now.

**Comment by NSoiffer** [comment]
Looks good. I probably would have just made the table global rather than have a function that returns it, but what you have is fine.

**Comment by NSoiffer** [comment]
I merged it in. Your code is working, but MathCAT seems to be stuck on
English in NVDA (changing languages works fine stand-alone). We might need
to add a "User Preference" option where the language used matches the
language NVDA is set to use (we'll make up a code like "default" that can't
match anything but has a nice display "User Preference (default)" . Don't
make a change until I figure this out though. I'm off to get some exercise
while the rain (and wind) have stopped, so you probably won't hear from me
until tomorrow your time.

    Neil

**Pull request merged**
